name: Deploy Node App (ECR + EC2)

on:
  push:
    branches:
      - main


env:
    AWS_REGION: us-east-2
    ECR_REPOSITORY: unimar-pos-fullstack
    IMAGE_TAG: latest

jobs:
    deploy:
            runs-on: ubuntu-latest

            steps:
              - name: Checkout código
                uses: actions/checkout@v4

        # 🔐 Autenticação AWS
              - name: Configurar credenciais AWS
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-2

        # 🔑 Login ECR via TOKEN (importante)
              - name: 🔑 Login no ECR
                uses: aws-actions/amazon-ecr-login@v2

        # 🐳 Build da imagem
              - name: Build Docker
                run: |
                    docker build -t $ECR_REPOSITORY .

              - name: 🏷️ Tag da imagem
                run: |
                  IMAGE_NAME=$ECR_REPOSITORY
                  docker tag $IMAGE_NAME:latest $ECR_REPOSITORY:latest

        # 📤 Push para ECR
              - name: 📦 Definir URI do ECR
                run: |
                  ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
                  echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV


              - name: 🚀 Deploy via SSH
                uses: appleboy/ssh-action@v1.0.3
                with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                    set -e

                    AWS_REGION=us-east-2
                    ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
                    REPOSITORY=unimar-pos-fullstack

                    IMAGE=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY}:latest

                    echo "📦 Verificando dependências..."

                    # Instalar Docker se não existir
                    if ! command -v docker &> /dev/null; then
                      echo "🐳 Instalando Docker..."
                      sudo apt update
                      sudo apt install -y docker.io
                      sudo systemctl start docker
                      sudo systemctl enable docker
                      sudo usermod -aG docker ubuntu
                    fi

                    # Instalar AWS CLI se não existir
                    if ! command -v aws &> /dev/null; then
                      echo "☁️ Instalando AWS CLI..."
                      sudo apt install -y awscli
                    fi

                    echo "🔑 Login no ECR..."
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                    echo "📥 Pull da imagem"
                    docker pull $IMAGE

                    echo "🛑 Parando container antigo"
                    docker stop my-node-app || true
                    docker rm my-node-app || true

                    echo "🚀 Subindo novo container"
                    docker run -d \
                      --name my-node-app \
                      -p 3000:3000 \
                      --restart always \
                      $IMAGE